# What on Earth is a pyproject.toml file?
# PEP 518 defines pyproject.toml as a configuration file to store build system requirements for Python projects.
# With the help of tools like Poetry or Flit it can fully replace the need for setup.py and setup.cfg files.
# https://github.com/toml-lang/toml

[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"