/***
 *
 * This file is autogenerated by:
 *       ______ ____   ___     _   __ ____ ______ ______
 *      / ____// __ \ /   |   / | / //  _//_  __// ____/
 *     / / __ / /_/ // /| |  /  |/ / / /   / /  / __/   
 *    / /_/ // _, _// ___ | / /|  /_/ /   / /  / /___   
 *    \____//_/ |_|/_/  |_|/_/ |_//___/  /_/  /_____/   
 *
 */
#ifndef     _INC_HEADER_FILE_DEFAULT
#   define  _INC_HEADER_FILE_DEFAULT
#   ifdef   __cplusplus
        extern "C" 
        {
#   endif

typedef struct __StandbyTelecommand__ {
	unsigned char			NameStandbyField_2;
	char			NameStandbyField_2;
	unsigned long			NameStandbyField_3;
	unsigned long long			NameStandbyField_4;
	signed char			NameStandbyField_5;
} TypStandbyTelecommand;

typedef struct __FrameTelecommand__ {
	char			NameFrameTcField_1;
	char			NameFrameTcField_2;
	char			NameFrameTcField_3;
	char			NameFrameTcField_4;
	char			NameFrameTcField_5;
} TypFrameTelecommand;

#   ifdef   __cplusplus
        }
#   endif
#endif /* _INC_HEADER_FILE_DEFAULT */
