/***
 *
 * This file is autogenerated by:
 *       ______ ____   ___     _   __ ____ ______ ______
 *      / ____// __ \ /   |   / | / //  _//_  __// ____/
 *     / / __ / /_/ // /| |  /  |/ / / /   / /  / __/   
 *    / /_/ // _, _// ___ | / /|  /_/ /   / /  / /___   
 *    \____//_/ |_|/_/  |_|/_/ |_//___/  /_/  /_____/   
 *
 */
#ifndef     _INC_HEADER_FILE_DEFAULT
#   define  _INC_HEADER_FILE_DEFAULT
#   ifdef   __cplusplus
        extern "C" 
        {
#   endif

typedef struct __StandbyTelecommand__ {
	unsigned char			NameStandbyField_2;
	char			NameStandbyField_2;
	unsigned long			NameStandbyField_3;
	unsigned long long			NameStandbyField_4;
	signed char			NameStandbyField_5;
} TypStandbyTelecommand;

typedef struct __FrameTelecommand__ {
	unsigned int			ShutterTime;
	float			SensorGain;
} TypFrameTelecommand;

typedef struct __CameraAutoExposure__ {
	unsigned char			enable;
	unsigned int			ShutterTime;
	float			SensorGain;
} TypCameraAutoExposure;

typedef struct __CameraFlash__ {
	unsigned char			enable;
	unsigned char			strength;
} TypCameraFlash;

typedef struct __CameraRegion __ {
	unsigned char			enable;
	unsigned char			planar;
} TypCameraRegion ;

typedef struct __CameraRegion __ {
	unsigned char			enable;
	unsigned short			pattern_sequence;
} TypCameraRegion ;

#   ifdef   __cplusplus
        }
#   endif
#endif /* _INC_HEADER_FILE_DEFAULT */
