/***
 *
 * This file is autogenerated by:
 *       ______ ____   ___     _   __ ____ ______ ______
 *      / ____// __ \ /   |   / | / //  _//_  __// ____/
 *     / / __ / /_/ // /| |  /  |/ / / /   / /  / __/   
 *    / /_/ // _, _// ___ | / /|  /_/ /   / /  / /___   
 *    \____//_/ |_|/_/  |_|/_/ |_//___/  /_/  /_____/   
 *
 */
#ifndef     _INC_HEADER_FILE_DEFAULT
#   define  _INC_HEADER_FILE_DEFAULT
#   ifdef   __cplusplus
        extern "C" 
        {
#   endif

typedef struct __ToFRegion__ {
	unsigned char			enable;
	unsigned char			region;
} TypToFRegion;

typedef struct __ToFRange__ {
	float			min_depth;
	float			max_depth;
} TypToFRange;

typedef struct __ToFConfiguration__ {
	unsigned char			region_enabled;
	unsigned char			region;
	float			min_depth;
	float			max_depth;
} TypToFConfiguration;

#   ifdef   __cplusplus
        }
#   endif
#endif /* _INC_HEADER_FILE_DEFAULT */
